### ISSUE TITLE
Set Min and Max Y-Axis Values?

### ISSUE THREAD

**Issue by dookie454** [paultheman/BME280_webserver#1]
Hello!  I've been using your HTM code to display temp/humidity and it is great!   Is there a way to set the min and max Y-Axis values manually rather than autoscale as it is currently setup?

Been trying to insert this into different places with no luck:
yAxis:  max: 200,

UPDATE:  I forgot the comma and had other syntax wrong!   lol.   Added it to the above.  Anyway, thanks

**Comment by paultheman** [comment]
Hi,
try this
```
yAxis: [{
	min: 10,
	max: 20,
	title: {
                text: 'Temperature °C'
            },
            id: 'T'
    },
```
